### PR TITLE
Single link list

### PR DESCRIPTION
**Pull request by HarryWillis0**
When I am creating an object that uses generics in a separate class, the following both work:

Node<T> node = new Node(item);

Node<T> node = new Node<T>(item);

Do you know if one is better than the other? 
Can't seem to find a good answer.

### CODE REVIEW

**Comment by SamuelWillis** [comment]
> When I am creating an object that uses generics in a separate class, the following both work:
> 
> Node node = new Node(item);
> 
> Node node = new Node(item);
> 
> Do you know if one is better than the other?
> Can't seem to find a good answer.

They both look the same to me?

**Comment by HarryWillis0** [comment]
Node\<T\>

**Comment by HarryWillis0** [comment]
Node\<T\> node = new Node(item);

Node\<T\> node = new Node\<T\>(item);

**Comment by SamuelWillis** [comment]
I'd do the `Node<T> node = new Node<T>(item);` just because it is clearer that the node's generic type is the same as the generic type of the linked list?

I am pretty hazy on Java best practices though so you might want to dig around. 

I'm also pretty hazy on how you import classes into other classes but you might not be using the `Node` class you made in this repo and instead are using the Java built-in `Node` class. It would be worth checking that out.

**Comment by HarryWillis0** [comment]
> I'd do the `Node<T> node = new Node<T>(item);` just because it is clearer that the node's generic type is the same as the generic type of the linked list?
> 
> I am pretty hazy on Java best practices though so you might want to dig around.
> 
> I'm also pretty hazy on how you import classes into other classes but you might not be using the `Node` class you made in this repo and instead are using the Java built-in `Node` class. It would be worth checking that out.

I'll look into it, but I don't think I'm using the built-in. My function names would have to be the exact same wouldn't they?

**Comment by SamuelWillis** [comment]
Yeah, good point. worth checking out though.

**Pull request merged**
